import type { EnginePath, Question } from "@/types/adaptive-engine";

/** Offline fallback question bank — mirrors migration 003 seed. */
export const SEED_QUESTIONS: Question[] = [
  {
    id: "dls_role",
    path: "do_i_love_someone",
    category: "foundation",
    question_text: "Who is this person in your life?",
    type: "single_select",
    options: [
      { label: "Friend", value: "friend" },
      { label: "Best friend", value: "best_friend" },
      { label: "Classmate", value: "classmate" },
      { label: "Coworker", value: "coworker" },
      { label: "Someone I recently met", value: "recently_met" },
      { label: "Ex", value: "ex" },
    ],
    psychological_dimension: "attachment",
    weight: 1,
    priority: 100,
    is_starter: true,
    follow_up_rules: {},
    scoring: {
      single_select: {
        friend: { attachment: 8 },
        best_friend: { attachment: 14, trust: 6 },
        recently_met: { crush: 10 },
        ex: { attachment: 6, love: -5 },
      },
    },
    confidence_value: 0.08,
  },
  {
    id: "dls_think_often",
    path: "do_i_love_someone",
    category: "emotional",
    question_text: "How often do you think about them?",
    type: "slider",
    options: { min: 1, max: 10 },
    psychological_dimension: "love",
    weight: 1.2,
    priority: 90,
    is_starter: true,
    follow_up_rules: {},
    scoring: {
      slider: {
        scale: { love: 2.5, crush: 1.5, attachment: 1 },
        confidence: 0.14,
      },
    },
    confidence_value: 0.14,
  },
  {
    id: "dls_excited",
    path: "do_i_love_someone",
    category: "emotional",
    question_text: "How excited are you to see or talk to them?",
    type: "slider",
    options: { min: 1, max: 10 },
    psychological_dimension: "crush",
    weight: 1.1,
    priority: 85,
    follow_up_rules: {},
    scoring: {
      slider: {
        scale: { crush: 2.8, love: 1.2, physical_attraction: 1.5 },
        confidence: 0.13,
      },
    },
    confidence_value: 0.13,
  },
  {
    id: "dls_miss",
    path: "do_i_love_someone",
    category: "emotional",
    question_text: "Do you miss them when they are not around?",
    type: "single_select",
    options: [
      { label: "Never", value: "never" },
      { label: "Sometimes", value: "sometimes" },
      { label: "Often", value: "often" },
      { label: "Almost always", value: "almost_always" },
      { label: "Not sure", value: "not_sure" },
    ],
    psychological_dimension: "attachment",
    weight: 1,
    priority: 80,
    follow_up_rules: {},
    scoring: {
      single_select: {
        never: { attachment: -8 },
        sometimes: { attachment: 8, love: 4 },
        often: { attachment: 16, love: 10 },
        almost_always: { attachment: 22, love: 14 },
        not_sure: { attachment: 2 },
      },
    },
    confidence_value: 0.12,
  },
  {
    id: "dls_trust",
    path: "do_i_love_someone",
    category: "trust",
    question_text: "How much do you trust them with your feelings?",
    type: "slider",
    options: { min: 1, max: 10 },
    psychological_dimension: "trust",
    weight: 1.4,
    priority: 88,
    follow_up_rules: {
      only_if: [{ type: "dimension_uncertain", dimension: "trust", below: 0.55 }],
    },
    scoring: {
      slider: { scale: { trust: 3.2, love: 1, attachment: 1 }, confidence: 0.15 },
    },
    confidence_value: 0.15,
  },
  {
    id: "dls_future",
    path: "do_i_love_someone",
    category: "future",
    question_text: "Can you imagine a future with them?",
    type: "single_select",
    options: [
      { label: "No", value: "no" },
      { label: "Maybe", value: "maybe" },
      { label: "Yes, clearly", value: "yes" },
      { label: "Not sure", value: "not_sure" },
    ],
    psychological_dimension: "future",
    weight: 1.2,
    priority: 82,
    follow_up_rules: {
      skip_if: [{ type: "dimension_below", dimension: "love", threshold: 25 }],
    },
    scoring: {
      single_select: {
        no: { future: -15, love: -8 },
        maybe: { future: 12, love: 8 },
        yes: { future: 28, love: 18, attachment: 10 },
        not_sure: { future: 5 },
      },
    },
    confidence_value: 0.13,
  },
  {
    id: "dls_clarify_miss",
    path: "do_i_love_someone",
    category: "clarification",
    question_text:
      "When you say you are unsure about missing them — is that because the feeling is mild, or because you have not noticed yet?",
    type: "single_select",
    options: [
      { label: "The feeling is mild or inconsistent", value: "mild" },
      { label: "I have not noticed yet", value: "not_noticed" },
      { label: "I am confused about what I feel", value: "confused" },
    ],
    psychological_dimension: "attachment",
    weight: 0.8,
    priority: 95,
    parent_question_id: "dls_miss",
    is_clarification: true,
    follow_up_rules: {},
    scoring: {
      single_select: {
        mild: { attachment: 6 },
        not_noticed: { attachment: 2 },
        confused: { attachment: 4, love: 3 },
      },
    },
    confidence_value: 0.1,
  },
  {
    id: "dsl_role",
    path: "does_someone_love_me",
    category: "foundation",
    question_text: "Who is this person in your life?",
    type: "single_select",
    options: [
      { label: "Friend", value: "friend" },
      { label: "Best friend", value: "best_friend" },
      { label: "Classmate", value: "classmate" },
      { label: "Coworker", value: "coworker" },
      { label: "Someone I recently met", value: "recently_met" },
      { label: "Ex", value: "ex" },
    ],
    psychological_dimension: "attachment",
    weight: 1,
    priority: 100,
    is_starter: true,
    follow_up_rules: {},
    scoring: {
      single_select: {
        friend: { attachment: 8 },
        best_friend: { attachment: 12 },
        recently_met: { crush: 8 },
      },
    },
    confidence_value: 0.08,
  },
  {
    id: "dsl_engagement",
    path: "does_someone_love_me",
    category: "communication",
    question_text: "How engaged are they when talking with you?",
    type: "slider",
    options: { min: 1, max: 10 },
    psychological_dimension: "communication",
    weight: 1.3,
    priority: 92,
    is_starter: true,
    follow_up_rules: {},
    scoring: {
      slider: {
        scale: { communication: 3, love: 1.5, crush: 1 },
        confidence: 0.15,
      },
    },
    confidence_value: 0.15,
  },
  {
    id: "dsl_support",
    path: "does_someone_love_me",
    category: "trust",
    question_text: "When you are upset, how do they respond?",
    type: "single_select",
    options: [
      { label: "Ignore it", value: "ignore" },
      { label: "Basic support", value: "basic" },
      { label: "Comfort me", value: "comfort" },
      { label: "Go out of their way", value: "extra" },
      { label: "Not sure", value: "not_sure" },
    ],
    psychological_dimension: "trust",
    weight: 1.2,
    priority: 88,
    follow_up_rules: {},
    scoring: {
      single_select: {
        ignore: { trust: -18, love: -14 },
        basic: { trust: 8, love: 6 },
        comfort: { trust: 18, love: 14, attachment: 10 },
        extra: { trust: 28, love: 22, attachment: 16 },
        not_sure: { trust: 4 },
      },
    },
    confidence_value: 0.14,
  },
  {
    id: "dsl_clarify_support",
    path: "does_someone_love_me",
    category: "clarification",
    question_text:
      "When you are unsure about their support — is it inconsistent, or have you not tested it yet?",
    type: "single_select",
    options: [
      { label: "Inconsistent", value: "inconsistent" },
      { label: "Have not tested it", value: "untested" },
      { label: "Hard to read their intentions", value: "hard_to_read" },
    ],
    psychological_dimension: "trust",
    weight: 0.8,
    priority: 95,
    parent_question_id: "dsl_support",
    is_clarification: true,
    follow_up_rules: {},
    scoring: {
      single_select: {
        inconsistent: { trust: 4 },
        untested: { trust: 2 },
        hard_to_read: { trust: 3, communication: -4 },
      },
    },
    confidence_value: 0.1,
  },
];

export function getSeedQuestionsForPath(path: EnginePath): Question[] {
  return SEED_QUESTIONS.filter((q) => q.path === path && q.is_active !== false);
}
